#!/bin/bash

if ! git rev-parse --is-inside-work-tree &>/dev/null; then   
    echo "Not a Git repository"
    exit 1 
fi

msg="${*:-Update changes}"

git add .

git commit -m "$msg"

branch=$(git rev-parse --abbrev-ref HEAD)
git push origin "$branch"

url=$(git config --get remote.origin.url)

if [[ $url == git@github.com:* ]]; then
  url="${url/git@github.com:/https:\/\/github.com\/}"
  url="${url/.git/}"
elif [[ $url == https://github.com/* ]]; then
  url="${url/.git/}"
else
  echo "Couldn't detect GitHub repo URL."
  exit 0
fi

if command -v xdg-open &>/dev/null; then
  xdg-open "$url"
elif command -v open &>/dev/null; then
  open "$url"
else
  echo "Could not open browser. Here's the link:"
  echo "$url"
fi
