#!/bin/bash

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "Not a Git repository"
    exit 1
fi

echo "Branch: &(git rev-parse --abbrev-ref HEAD)"

echo -e "\n Status:"
git status -sb

echo -e "\n Recent Commits:"
git log --oneline -n 3
