#!/bin/bash

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "Not a Git repository."
    exit 1
fi

user_name       = $(git config user.name)
user_email      = $(git config user.email)
branch          = $(git rev-parse --abbrev-ref HEAD)
remote_url      = $(git config --get remote.origin.url)
last_commig_msg = $(git log -1 --pretty=%B)

echo "Git user: $user_name <$user_email>"
echo "Branch: $branch"
echo "Remote: $remote_url"
echo "Last Commit: $last_commig_msg"